#ifndef SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_
#define SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_

//
// Copyright (C) 2025  HiPES - Universidade Federal do Paraná
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

/**
 * @file trace_reader.hpp
 * @brief Implementation of sinuca trace reader suitable for traces generated by
 * single or multi threaded applications. It implements the interface defined
 * in tracer/trace_reader.hpp file.
 */

#include <tracer/sinuca/file_handler.hpp>
#include <tracer/trace_reader.hpp>

#include "engine/default_packets.hpp"

int OpenTraceAndCreateLoader(const char* dir, const char* prefix, char** path,
                             int tid, bool tidOut, Reader* reader);

struct Thread {
    Reader executionLoader;
    Reader memoryLoader;

    char* pathToDynamicTrace;
    char* pathToMemoryTrace;

    long currentBasicBlock;
    long currentInstruction;
    long currentBblSize;
    long fetchCount;

    bool needToFetchNewBasicBlock;
    bool isWaitingForCriticalSection;
    bool isInsideCriticalSection;
    bool waitingAtBarrier;
    bool hasEndedExecution;

    int tid;

    Thread()
        : pathToDynamicTrace(0),
          pathToMemoryTrace(0),
          currentBasicBlock(0),
          currentInstruction(0),
          fetchCount(0),
          needToFetchNewBasicBlock(true),
          isWaitingForCriticalSection(false),
          isInsideCriticalSection(false),
          waitingAtBarrier(false),
          hasEndedExecution(false),
          tid(-1) {}

    /** @brief Initialize the thread. */
    int Setup(const char* directory, int tid);
    /** @brief Open the execution log for the thread. */
    int OpenExecutionLog(const char* directory);
    /** @brief Open the memory log for the thread. */
    int OpenMemoryLog(const char* directory);
    /** @brief Set the current basic block for the thread. */
    void SetBasicBlock(int bbl, int size);
    /** @brief Step to the next instruction in the current basic block. */
    void StepInstruction();

    ~Thread();

    inline void SetTid(int tid) {
        assert(tid >= 0);
        this->tid = tid;
    }
    inline void SetArrivedAtBarrier() {
        this->waitingAtBarrier = true;
    }
    inline void SetLeftBarrier() {
        this->waitingAtBarrier = false;
    }
    inline void SetWaitingForCriticalSection() {
        this->isWaitingForCriticalSection = true;
    }
    inline void SetInsideCriticalSection() {
        this->isInsideCriticalSection = true;
        this->isWaitingForCriticalSection = false;
    }
    inline void SetExitedCriticalSection() {
        this->isInsideCriticalSection = false;
    }
    inline void SetHasEndedExecution(bool ended) {
        this->hasEndedExecution = ended;
    }
    inline void SetNeedToFetchNewBasicBlock(bool need) {
        this->needToFetchNewBasicBlock = need;
    }
    inline bool IsThreadWaiting() const {
        return this->isWaitingForCriticalSection || this->waitingAtBarrier;
    }
    inline bool HasThreadEndedExecution() const {
        return this->hasEndedExecution;
    }
    inline bool NeedToFetchNewBasicBlock() const {
        return this->needToFetchNewBasicBlock;
    }
};

struct BasicBlock {
    StaticInstructionInfo* instructions;
    long size;
};

/** @brief Check trace_reader.hpp documentation for details */
class SinucaTraceReader : public TraceReader {
  private:
    Reader instructionsLoader;

    BasicBlock* dictionary;
    StaticInstructionInfo* pool;
    Thread* threads;

    char* pathToStaticFile;

    int threadCount;
    int bblocksCount;
    int recordedInst;

    /* For statistics */
    int barriers;
    int criticalSections;

    /** @brief Create threads for handling the trace. */
    int CreateThreads(const char* directory);
    /** @brief Check if the thread is sleeping. */
    int IsThreadSleeping(int tid);
    /** @brief Check if the thread is inside a basic block. */
    int IsThreadInsideBasicBlock(int tid);
    /** @brief Try to fetch a new basic block. */
    int TryToFetchNewBasicBlock(int tid);
    /** @brief Check if the thread performs a memory access. */
    int PerformsMemoryAccess(const StaticInstructionInfo* inst);
    /** @brief Fill instructions dictionary. */
    int GenerateDictionaryOfInstructions();
    /** @brief Check if the execution has ended. */
    int HasExecutionEnded();
    /** @brief Check if all threads have the same version and target */
    int VerifyVersionAndTarget();
    /** @brief Read the metadata from the trace file. */
    int ReadMetadata();
    /** @brief Open the instructions log. */
    int OpenInstructionsLog(const char* directory);
    /** @brief Try to wake up thread. Returns true if successful. */
    bool TryToWakeUpThread(int tid);
    /** @brief Fetch an instruction from the trace. */
    void FetchInstruction(InstructionPacket* ret, int tid);
    /** @brief Call if the instruction has no memory access. */
    void FillEmptyAccess(InstructionPacket* ret);
    /** @brief Fetch a memory access from the trace. */
    void FetchMemoryAccess(InstructionPacket* ret, int tid);
    /** @brief Handle a thread event. */
    void HandleEvent(int tid, EventType event);
    /** @brief Handle a barrier synchronization event. */
    void HandleBarrierSync(int tid);
    /** @brief Handle the start of a critical section. */
    void HandleCriticalStart(int tid);
    /** @brief Handle the end of a critical section. */
    void HandleCriticalEnd(int tid);
    /** @brief Handle an abrupt end of thread execution. */
    void HandleAbruptEnd();
    /** @brief Deallocate all allocated resources. */
    void DeallocateResources();
    /** @brief Print the headers of the trace files. */
    void PrintHeaders();
    /** @brief Format the directory path. */
    char* FormatDirectory(const char* directory);

  public:
    SinucaTraceReader()
        : dictionary(0),
          pool(0),
          threads(0),
          pathToStaticFile(0),
          threadCount(0),
          bblocksCount(0),
          recordedInst(0),
          barriers(0),
          criticalSections(0) {}

    virtual FetchResult Fetch(InstructionPacket* ret, int tid);
    virtual int OpenTrace(const char* directory);
    virtual void PrintStatistics();
    virtual long GetNumberOfFetchedInst(int tid);
    virtual long GetTotalInstToBeFetched(int tid);
    virtual int GetTotalThreads();
    virtual int GetTotalBasicBlocks();

    virtual ~SinucaTraceReader();
};

#endif  // SINUCA3_SINUCA_TRACER_TRACE_READER_HPP_
